
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { signOut } from 'next-auth/react';

import Button from '@mui/material/Button';
import { getSession } from 'next-auth/react';


const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Button
          onClick={() => signOut()}
          variant="contained"
          color="secondary"
        >
          Sign out
        </Button>

        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          </div>
          </main>
          </>
          )
};

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  if (!session) {
      return {
          redirect: {
              destination: '/auth/signin',
              permanent: false,
          },
      };
  }
  return {
      props: { session },
  };
}
